# Generated by Django 6.0.3 on 2026-03-13 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home'), ('reserve', 'Reserve'), ('order', 'Order'), ('gallery', 'Gallery'), ('reviews', 'Reviews'), ('menu', 'Menu'), ('contact', 'Contact')], max_length=200),
        ),
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('button_type', models.CharField(choices=[('reserve', 'Reserve'), ('order', 'Order'), ('login', 'Login'), ('register', 'Register')], max_length=20)),
                ('icon_type', models.CharField(choices=[('calendar', 'Calendar'), ('globe', 'Globe'), ('user', 'User'), ('user_plus', 'UserPlus')], default='globe', max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='buttons/icons/')),
                ('url', models.URLField(blank=True, max_length=300)),
                ('url_name', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_auth', models.BooleanField(default=False)),
                ('guests_only', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurant')),
            ],
        ),
    ]
